const coremembers = [
    {
        id:1,
        name: "Rishabh Jain",
        position: "Chairperson",
        info: "Robotics & Automation",
        profile: "/images/coreteam-images/rishabh.png",
        insta: "https://www.instagram.com/rishabhjain2010/",
        linkedin: "https://www.linkedin.com/in/rishabhjain2010/",
        github: "https://github.com/rishabhjain2010",
    },
    {
        id:2,
        name: "Prachi Singh",
        position: "Vice-Chairperson",
        info: "Web Developer",
        profile: "/images/coreteam-images/prachi.png",
        insta: "https://www.instagram.com/prachi_09._.7/",
        linkedin: "https://www.linkedin.com/in/prachi-singh-3082a620a",
        github: "https://github.com/PrachiSingh09",
    },
    {
        id:3,
        name: "Utkarsh Jha",
        position: "Event Head",
        info: "Software Developer",
        profile: "/images/coreteam-images/utkarsh-y.png",
        insta: "https://www.instagram.com/utkarshjha_/",
        linkedin: "https://www.linkedin.com/in/utkarsh-jha-378b36215/",
        github: "https://github.com/UtJha",
    },
    {
        id:4,
        name: "Tushar Patodia",
        position: "Technical Head",
        info: "Blockchain Developer",
        profile: "/images/coreteam-images/tushar.jpeg",
        insta: "https://www.instagram.com/13.tush/",
        linkedin: "https://www.linkedin.com/in/tushar-patodia-0150a4235",
        github: "https://github.com/nerdTushar",
    },
    {
        id:5,
        name: "Oshank",
        position: "Cyber Security Head",
        info: "Cyber Security",
        profile: "/images/coreteam-images/oshank-y.png",
        insta: "https://www.instagram.com/_oshank/",
        linkedin: "https://www.linkedin.com/in/oshank-kashyap-280583201/",
        github: "https://github.com/OshankKashyap",
    },
    {
        id:6,
        name: "Vineet Bhatt",
        position: "Graphics Head",
        info: "UI/UX Developer",
        profile: "/images/coreteam-images/vineet.jpg",
        insta: "http://instagram.com/vineet__bhatt",
        linkedin: "https://www.linkedin.com/in/vineet-bhatt-1aaa8a234",
        github: "https://github.com/VINEET167",
    },
    {
        id:7,
        name: "Kushagra Singh",
        position: "Graphics Head",
        info: "UI/UX Developer",
        profile: "/images/coreteam-images/kushagra.jpg",
        insta: "https://www.instagram.com/_kushagra_singh_2003/",
        linkedin: "https://www.linkedin.com/in/kushagra-singh-705a46239/",
        github: "https://github.com/Kushagrasingh2003",
    },
    {
        id:8,
        name: "Chandni Kumari",
        position: "Graphics Head",
        info: "UI/UX Developer",
        profile: "/images/coreteam-images/chandni.jpg",
        insta: "https://www.instagram.com/chand__nii/",
        linkedin: "https://www.linkedin.com/in/chandni-kumari-10518a235",
        github: "https://github.com/chandnii96",
    },
    {
        id:9,
        name: "Meenakshi Panchal",
        position: "PR & Anchoring Head",
        info: "Full Stack Developer",
        profile: "/images/coreteam-images/meenakshi.png",
        insta: "https://www.instagram.com/_meenakshi.17/",
        linkedin: "https://www.linkedin.com/in/meenakshi-panchal-617393242/",
        github: "https://github.com/meenakshipanchal17",
    },
    {
        id:10,
        name: "Arsh Kumar",
        position: "Social media Head",
        info: "App Developer",
        profile: "/images/coreteam-images/arsh.jpg",
        insta: "https://www.instagram.com/only._.arshh/",
        linkedin: "https://www.linkedin.com/in/arsh-kumar-a12a95224",
        github: "https://github.com/arsh-kum04",
    },
    {
        id:11,
        name: "Sejal Talwar",
        position: "Campus Mantri",
        info: "Content Writer",
        profile: "/images/coreteam-images/sejal.png",
        insta: "https://www.instagram.com/sejaltalwarr/",
        linkedin: "https://www.linkedin.com/in/sejal-talwar-ba7099222/",
        github: "",
    },
]

export default coremembers;