const extendmembers = [
    {
        id:1,
        name: "Prajwal Pandey",
        position: "Volunteer",
        info: "Alpha",
        profile: "/images/extendedteam-images/prajwal.jpeg",
        insta: "https://instagram.com/_prajwal_pandey?igshid=ZDdkNTZiNTM=",
        linkedin: "https://www.linkedin.com/in/prajwal-pandey-86b6b4261/",
        github: "https://github.com/technocorpse567i",
    },
    {
        id:2,
        name: "Rupashi",
        position: "Volunteer",
        info: "Omega",
        profile: "/images/extendedteam-images/rupashi.jpeg",
        insta: "https://instagram.com/ambient_bliss3012?igshid=NmQ2ZmYxZjA=",
        linkedin: "https://www.linkedin.com/in/rupashi-a2b6a2261",
        github: "https://github.com/isthatashi",
    },
    {
        id:3,
        name: "Vandita Gaba",
        position: "Volunteer",
        info: "Gamma",
        profile: "/images/extendedteam-images/vandita.jpeg",
        insta: "https://www.instagram.com/gaba_vandita/",
        linkedin: "https://www.linkedin.com/in/vandita-gaba-0a845825a",
        github: "https://github.com/Vanditagaba",
    },
    {
        id:4,
        name: "Jaishree",
        position: "Volunteer",
        info: "Sigma",
        profile: "/images/extendedteam-images/jaishree.jpeg",
        insta: "https://www.instagram.com/_jaishree29/",
        linkedin: "https://www.linkedin.com/in/jaishree-tiwari-54212925b/",
        github: "https://github.com/jaishree29",
    },
    {
        id:5,
        name: "Krishna Kartikay Bhatt",
        position: "Volunteer",
        info: "Delta",
        profile: "/images/extendedteam-images/kkbhat.jpg",
        insta: "https://www.instagram.com/imkk.bhatt07/?next=%2F&hl=en",
        linkedin: "https://www.linkedin.com/in/krishna-kartikay-bhatt",
        github: "https://github.com/kkbhatt07",
    },
    {
        id:6,
        name: "Chahat Chhabra",
        position: "Volunteer",
        info: "Thetha",
        profile: "/images/extendedteam-images/chahat.jpeg",
        insta: "https://instagram.com/chahat__2512?igshid=Mzc0YWU1OWY=",
        linkedin: "https://www.linkedin.com/in/chahat-chhabra-756342260",
        github: "https://github.com/ChahatChh123/ChahatChh123",
    },
    {
        id:7,
        name: "Dipti",
        position: "Volunteer",
        info: "Lambda",
        profile: "/images/extendedteam-images/deepti.jpeg",
        insta: "https://instagram.com/drishtichahar15?igshid=Mzc0YWU1OWY=",
        linkedin: "https://www.linkedin.com/in/dipti-chahar-948a26247",
        github: "https://github.com/DiptiChahar",
    },
]

export default extendmembers;